### ISSUE TITLE
Erste Schritte

### ISSUE THREAD

**Issue by klepek42** [edgarklepek42/fhangmandw#1]
# ToDo-List
## Basics
- [x] Menü Struktur herstellen
- [x] Menü verschönern (CSS)
- [x] Game.html Grundstruktur herstellen
- [x] Array mit Wörtern erstellen
- [x] Zufällige Wortauswahl implementieren
- [x] FHDW Farben anwenden
## Advanced
- [x] Game: Button "nächstes Wort"
- [x] Alphabet als Buttons implementieren (Umsetzung mit Schleife)
- [x] Ratewortfeld in Abhängigkeit der Wortlänge implementieren
- [x] Punktelogik umsetzen
- [x] Geklickte Buttons deaktivieren (disable)
- [x] Einblendung für "Bestenliste" und "Anleitung"  (optional)
## Brainstorming
- [x] Sinn von Bestenliste überlegen
- [x] Wörter Auswahl überlegen
