### ISSUE TITLE
Letzte ToDo's

### ISSUE THREAD

**Issue by klepek42** [edgarklepek42/fhangmandw#10]
# GitHub
- [x] Readme auf deutsch übersetzen
- [x] Readme Aufgabenteilung nennen
- [x] Nicht verwendete Icons und Sounds aus Projekt entfernen
# Game/Code
- [x] Anleitung: Text verkleinern
- [x] Anleitung: blinkender Hinweis "Klick für zurück!"
- [x] Anleitung: CC Attribution zum Joker Icon
- [x] Game Over Übergang schön gestalten
- [x] Sound Bug... (Andere Sounds testen)
- [x] Joker Button deaktiveren Effekt oder zurück auf einfachen Button
- [x] Alle console.log Meldungen entfernen
# WordPress
- [x] Hintergrundbild austauschen
- [x] Fertigen Pitcher einbauen
- [x] Icon Attributions in Impressum
# Pitcher
- [x] Pitcher fertigstellen und in WordPress Seite einbinden
